// Static Information
//Added to database automatically
//when backend/app.js is launched

//Patient collection
const patients = [
  {
    PatientName: "Alice Cooper",
    Email: "acooper@email.com",
    Password: "password123",
    dateOfBirth: 19800101,
    phoneNumber: 1234567890,
    bloodGroup: "O+",
    height: 165,
    weight: 60,
    eireCode: "D01 XY23",
    Address: "123 Elm Street, Dublin 1, Ireland",
  },
  {
    PatientName: "Bob Dylan",
    Email: "BD1@email.com",
    Password: "securepass456",
    dateOfBirth: 19410524,
    phoneNumber: 1234567891,
    bloodGroup: "A+",
    height: 180,
    weight: 75,
    eireCode: "X91 XY12",
    Address: "202 Birch Boulevard, Waterford, Ireland",
  },
  {
    PatientName: "Carole King",
    Email: "CaroleK@email.com",
    Password: "mypassword000",
    dateOfBirth: 19420209,
    phoneNumber: 1234567892,
    bloodGroup: "B+",
    height: 162,
    weight: 55,
    eireCode: "H91 XY67",
    Address: "789 Pine Road, Galway, Ireland",
  },
  {
    PatientName: "David Bowie",
    Email: "dave47@email.com",
    Password: "bpass111",
    dateOfBirth: 19470108,
    phoneNumber: 1234567893,
    bloodGroup: "AB-",
    height: 175,
    weight: 70,
    eireCode: "V94 XY89",
    Address: "101 Maple Lane, Limerick, Ireland",
  },
  {
    PatientName: "Nina Simone",
    Email: "nina62@email.com",
    Password: "pass202word",
    dateOfBirth: 19330221,
    phoneNumber: 1234567894,
    bloodGroup: "O-",
    height: 170,
    weight: 65,
    eireCode: "T12 XY45",
    Address: "456 Oak Avenue, Cork, Ireland",
  },
  {
    PatientName: "Frank Sinatra",
    Email: "frankie@email.com",
    Password: "sin12345",
    dateOfBirth: 19151212,
    phoneNumber: 1234567895,
    bloodGroup: "A-",
    height: 178,
    weight: 72,
    eireCode: "F91 XY34",
    Address: "303 Cedar Court, Sligo, Ireland",
  },
];

//Prescription Collection
const prescriptions = [
  {
    MedicationName: "Amoxicillin",
    Dosage: "500 mg",
    Route: "Oral",
    Frequency: "Three times a day",
    DoctorName: "Dr. John Smith",
    PatientName: "Alice Cooper",
    PrescriptionDate: "2024-08-03",
  },
  {
    MedicationName: "Ibuprofen",
    Dosage: "200 mg",
    Route: "Oral",
    Frequency: "Every 4-6 hours as needed",
    DoctorName: "Dr. Emily White",
    PatientName: "Bob Dylan",
    PrescriptionDate: "2024-08-02",
  },
  {
    MedicationName: "Metformin",
    Dosage: "1000 mg",
    Route: "Oral",
    Frequency: "Twice a day",
    DoctorName: "Dr. Robert Brown",
    PatientName: "Carol King",
    PrescriptionDate: "2024-08-01",
  },
  {
    MedicationName: "Lisinopril",
    Dosage: "10 mg",
    Route: "Oral",
    Frequency: "Once a day",
    DoctorName: "Dr. Linda Green",
    PatientName: "David Bowie",
    PrescriptionDate: "2024-07-30",
  },
  {
    MedicationName: "Atorvastatin",
    Dosage: "20 mg",
    Route: "Oral",
    Frequency: "Once a day",
    DoctorName: "Dr. Michael Clark",
    PatientName: "David Bowie",
    PrescriptionDate: "2024-07-29",
  },
  {
    MedicationName: "Amlodipine",
    Dosage: "5 mg",
    Route: "Oral",
    Frequency: "Once a day",
    DoctorName: "Dr. Jennifer Lewis",
    PatientName: "Frank Sinatra",
    PrescriptionDate: "2024-07-28",
  },
  {
    MedicationName: "Hydrochlorothiazide",
    Dosage: "25 mg",
    Route: "Oral",
    Frequency: "Once a day",
    DoctorName: "Dr. Emily White",
    PatientName: "Bob Dylan",
    PrescriptionDate: "2024-07-26",
  },
  {
    MedicationName: "Gabapentin",
    Dosage: "300 mg",
    Route: "Oral",
    Frequency: "Three times a day",
    DoctorName: "Dr. Linda Green",
    PatientName: "Hamilton Niculescu",
    PrescriptionDate: "2024-07-24",
  },
];

//Exports collections
module.exports = {
  prescriptions,
  patients,
};
